export const COMPLETION_POPUP_WIDTH = 460;
export const COMPLETION_POPUP_HEIGHT = 340;
export const COMPLETION_POPUP_MARGIN = 12;
export const COMPLETION_POPUP_GAP = 4;
export const COMPLETION_PAGE_STEP = 6;
export const COMPLETION_POPUP_FALLBACK_POSITION = { top: 96, left: 280 };

export const SDK_INDEX_READY_WAIT_ATTEMPTS = 120;
export const SDK_INDEX_READY_WAIT_INTERVAL_MS = 50;

export const LEFT_SIDEBAR_DEFAULT_WIDTH = 316;
export const LEFT_SIDEBAR_COLLAPSED_WIDTH = 62;
export const LEFT_SIDEBAR_MIN_WIDTH = 220;
export const LEFT_SIDEBAR_MAX_WIDTH = 520;

export const LAZY_PROJECT_TREE_FILE_THRESHOLD = 1_000;
export const WORKSPACE_INDEX_WATCH_INTERVAL_MS = 5_000;
export const SEARCH_EVERYWHERE_DISPLAY_LIMIT = 24;
